# Generated by Django 3.0 on 2019-12-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
